In [3]:
##########Bag of Words (BoW) Feature Extraction##########

In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.DataFrame({
    'text': ['people love coding',
             'love is coding',
             'i love coding',
             'coding is fun'], 'output':[1,1,0,0]})
df

text  output
0  people love coding       1
1      love is coding       1
2       i love coding       0
3       coding is fun       0

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bow = cv.fit_transform(df['text'])
print(cv.vocabulary_)
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())
print(bow.toarray())


{'people': 4, 'love': 3, 'coding': 0, 'is': 2, 'fun': 1}
[[1 0 0 1 1]]
[[1 0 1 1 0]]
[[1 0 0 1 0]]
[[1 1 1 0 0]]
[[1 0 0 1 1]
 [1 0 1 1 0]
 [1 0 0 1 0]
 [1 1 1 0 0]]


In [7]:
##############n-grams Feature Extraction##############

In [8]:
df2 = pd.DataFrame({
    'text': ['people love coding',
                'love is coding',
                'i love coding',
                'coding is fun'], 'output':[1,1,0,0]})

from sklearn.feature_extraction.text import CountVectorizer
cv2 = CountVectorizer(ngram_range=(1,1)) # unigrams
bow2 = cv2.fit_transform(df2['text'])
print(bow2.toarray())
print("Unigrams Vocabulary: ", cv2.vocabulary_)

cv3 = CountVectorizer(ngram_range=(2,2)) # bigrams
bow3 = cv3.fit_transform(df2['text'])
print(bow3.toarray())
print("Bigrams Vocabulary: ", cv3.vocabulary_)

[[1 0 0 1 1]
 [1 0 1 1 0]
 [1 0 0 1 0]
 [1 1 1 0 0]]
Unigrams Vocabulary:  {'people': 4, 'love': 3, 'coding': 0, 'is': 2, 'fun': 1}
[[0 0 0 1 0 1]
 [0 1 0 0 1 0]
 [0 0 0 1 0 0]
 [1 0 1 0 0 0]]
Bigrams Vocabulary:  {'people love': 5, 'love coding': 3, 'love is': 4, 'is coding': 1, 'coding is': 0, 'is fun': 2}


In [19]:
###############TF-IDF Feature Extraction###############
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()
# tfidf
# print(tfidf.idf_)

array([[0.40264194, 0.        , 0.        , 0.49248889, 0.77157901],
       [0.4574528 , 0.        , 0.69113141, 0.55953044, 0.        ],
       [0.63295194, 0.        , 0.        , 0.77419109, 0.        ],
       [0.37919167, 0.72664149, 0.5728925 , 0.        , 0.        ]])

In [21]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.         1.91629073 1.51082562 1.22314355 1.91629073]
['coding' 'fun' 'is' 'love' 'people']
